#!/usr/bin/env bash

function o {
	if [[ $# -eq 1 ]]; then
		selected=$1
	else
		selected=$(find ~/code -mindepth 1 -maxdepth 2 -type d | fzf)
	fi

	if [[ -z $selected ]]; then
		return 0
	fi

	selected_name=$(basename "$(dirname "$selected")")_$(basename "$selected")
	selected_name=$(echo "$selected_name" | tr . _)
	tmux_running=$(pgrep tmux)

	if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
		TMUX="" tmux new-session -ds "$selected_name" -c "$selected" -n "nvim" \; \
			send-keys "nvim" Enter \; \
			new-window -t "$selected_name:" -c "$selected" -n "shell" \; \
			select-window -t "$selected_name:nvim"
	fi

	if ! tmux has-session -t=$selected_name 2> /dev/null; then
		tmux new-session -ds "$selected_name" -c "$selected" -n "nvim" \; \
			send-keys "nvim" Enter \; \
			new-window -t "$selected_name:" -c "$selected" -n "shell" \; \
			select-window -t "$selected_name:nvim"
	fi

	if [[ -z "$TMUX" ]]; then
		tmux attach-session -t "$selected_name"
	else
		tmux switch-client -t "$selected_name"
	fi
}
