#!/usr/bin/env bash

function z {
	if [[ $# -eq 1 ]]; then
		selected=$1
	else
		selected=$(find ~/code -mindepth 1 -maxdepth 2 -type d | fzf)
	fi

	if [[ -z $selected ]]; then
		return 0
	fi

	selected_name=$(basename "$selected")
	selected_name=$(echo "$selected_name" | tr . _)

	local layout_path="$HOME/.config/zellij/layouts/dev.kdl"
	local sessions
	sessions=$(zellij list-sessions -s 2>&1 || true)

	if [[ "$sessions" != *"No active"* ]] && echo "$sessions" | grep -q "^$selected_name$"; then
		zellij attach "$selected_name"
	else
		(cd "$selected" && zellij --session "$selected_name" --new-session-with-layout "$layout_path")
	fi
}
