SPACESHIP_PROMPT_ORDER=(
	user
	host
	dir
	git
	exec_time
	exit_code
)
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_GIT_SHOW=true
SPACESHIP_GIT_STATUS_SHOW=true
SPACESHIP_GIT_BRANCH_SHOW=true
SPACESHIP_GIT_SYMBOL=" "

