"$schema" = "https://starship.rs/config-schema.json"

add_newline = false

[line_break]
disabled = true

[directory]
truncation_length = 8
truncate_to_repo = true

[character]
disabled = true

[package]
disabled = true

[aws]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true
