"$schema" = "https://starship.rs/config-schema.json"

add_newline = false

[line_break]
disabled = true

[directory]
truncation_length = 8
truncate_to_repo = true
style = "#519fdf"

[git_branch]
style = "#eeaf58"
symbol = ""

[git_status]
style = "#eeaf58"

[character]
disabled = true

[package]
disabled = true

[aws]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[docker_context]
disabled = true
