theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
true-color = true
auto-pairs = true
rulers = [80, 85]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "▏"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "total-line-numbers", "version-control", "spacer", "diagnostics", "workspace-diagnostics"]
center = ["file-name"]
right = ["selections", "primary-selection-length", "position", "position-percentage"]
